FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# test2

Hello !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Name**
`SERVER:` Raider
`CLIENT:` RenGer


## Hello [/name]
i am Hero **name** never.

### Name [GET]

+ Response 200 (application/json)

        {
            "name": "World"
        }